# Generated by Django 5.2.8 on 2025-11-23 08:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('north', 'North'), ('north-east', 'North-East'), ('east', 'East'), ('south-east', 'South-East'), ('south', 'South'), ('south-west', 'South-West'), ('west', 'West'), ('north-west', 'North-West')], help_text='alege directia', max_length=20)),
                ('distance', models.IntegerField(help_text='distanta in mile (mai mare ca 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(help_text='scrie o descriere')),
                ('risk_level', models.IntegerField(help_text='cat de periculos e (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('previous_instruction', models.OneToOneField(blank=True, help_text='leaga de pasul anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_instruction', to='treasure_hunt.instruction')),
            ],
        ),
    ]
