# Generated by Django 5.2.8 on 2025-11-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesajContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
                ('data_trimiterii', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
